# Author: Fábio Campos Ferreira
# Contains modules to train the classifiers using the features generated by **feature_extraction.py**
# In general, the modules receive the features to train the classifiers, these are saved in binary files with the same name as the classifier.

from sklearn.svm import SVC
import numpy as np
import cv2 as cv


def train(X, y, method_name, method, library):
    """Get features and class to train and save method"""
    if library == "OpenCV":
        X = np.matrix(X, dtype=np.float32)
        y = np.array(y)
        method.train(X, cv.ml.ROW_SAMPLE, y)
        method.save(method_name+".xml")
    elif library == "scikit-learn":
        pass


def SVM_create(library):
    """Create and return an OpenCV SVM classifier with the given options"""
    if library == "OpenCV":
        svm = cv.ml.SVM_create()
        svm.setType(cv.ml.SVM_C_SVC)
        svm.setC(1)
        svm.setKernel(cv.ml.SVM_LINEAR)
        return svm
    elif library == "scikit-learn":
        svm = SVC(C=1.0, kernel='linear')
        return svm
    
