# Author: Fábio Campos Ferreira
# Contains modules to train the classifiers using the features generated by **feature_extraction.py**
# In general, the modules receive the features to train the classifiers, these are saved in binary files with the same name as the classifier.

from sklearn.preprocessing import OneHotEncoder
from sklearn.svm import SVC
import numpy as np
import cv2 as cv


def train(X, y, method_name, method, library, xml_name):
    """Get features and class to train and save method"""
    if library == "OpenCV":
        X = np.matrix(X, dtype=np.float32)
        y = np.array(y)
        if method_name == "MLP":
            y = OneHotEncoder(sparse=False, dtype=np.float32).fit_transform(y.reshape(-1, 1))
        method.train(X, cv.ml.ROW_SAMPLE, y)
        method.save(xml_name.replace("XXX", method_name))
    elif library == "scikit-learn":
        pass


def MLP_create(library, mlp_layers):
    """Create and return an OpenCV MLP classifier with the given options"""
    if library == "OpenCV":
        mlp = cv.ml.ANN_MLP_create()
        mlp.setLayerSizes(np.array(mlp_layers))
        mlp.setActivationFunction(cv.ml.ANN_MLP_SIGMOID_SYM, 2.5, 1.0)
        mlp.setTrainMethod(cv.ml.ANN_MLP_BACKPROP)
        mlp.setTermCriteria((cv.TERM_CRITERIA_MAX_ITER + cv.TERM_CRITERIA_EPS, 300, 0.01))
        return mlp
    elif library == "scikit-learn":
        pass


def KNN_create(library: str, k: int):
    """Create and return an OpenCV KNN classifier with the given options"""
    if library == "OpenCV":
        knn = cv.ml.KNearest_create()
        knn.setDefaultK(k)
        return knn
    elif library == "scikit-learn":
        pass


def SVM_create(library):
    """Create and return an OpenCV SVM classifier with the given options"""
    if library == "OpenCV":
        svm = cv.ml.SVM_create()
        svm.setType(cv.ml.SVM_C_SVC)
        svm.setC(1)
        svm.setKernel(cv.ml.SVM_LINEAR)
        return svm
    elif library == "scikit-learn":
        svm = SVC(C=1.0, kernel='linear')
        return svm
